In [1]:
import numpy as np

## Numpy Array

In [2]:
benimListem = [20,30,40,50]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40, 50])

In [5]:
matrixListesi =[[10,20,30],[40,50,60],[40,78,88]]

In [6]:
matrixListesi[1][0]

40

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [40, 78, 88]])

In [8]:
type(np.array(matrixListesi))

numpy.ndarray

## Arange

In [9]:
list(range(0,10)) # Liste oluşturur

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10) # Numpy dizisi oluşturur

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# Linspace

In [12]:
np.linspace(0,100,100) # 0 ile 100 arasında 100 eşit aralıklı sayı

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

## Random

In [13]:
np.random.randn(4) # bu fonksiyon bize numoay dizisi dönderir

array([-0.85718617, -0.19288182,  2.2578211 ,  1.10672427])

In [14]:
np.random.randn(3,4)# bu fonksiyon bize numoay matrixi dönderir

array([[ 2.51758648, -0.3987873 ,  0.32994824,  1.40029881],
       [-2.27757577, -0.13055844,  1.447478  , -0.41624879],
       [-2.05756772,  0.38532363,  0.42005956,  0.38183668]])

In [15]:
np.random.randint(1,100) # 1 dem 100 e kadar tek bir değer dönderir

63

In [16]:
# 1 ile 300 arasında (300 dahil değil) rastgele 5 tam sayı üretir
result = np.random.randint(1, 300, 5)
result

array([ 56, 268, 200, 265, 230])

In [17]:
numpay = np.arange(0,10)

In [18]:
numpay

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
numpay = np.random.randint(0,100,12)

In [20]:
numpay

array([75, 86, 32, 46, 10, 98, 45, 91, 48, 53, 19, 83])

## Numpy Dizi Metodları

In [21]:
# Bu diziyi yeniden şekillendiriyoruz: 3 satır ve 4 sütundan oluşan bir matris
numpay1 = numpay.reshape(3, 4)
numpay1

array([[75, 86, 32, 46],
       [10, 98, 45, 91],
       [48, 53, 19, 83]])

In [22]:
numpay2 = numpay.reshape(4, 3)
numpay2

array([[75, 86, 32],
       [46, 10, 98],
       [45, 91, 48],
       [53, 19, 83]])

In [23]:
numpay.max()

98

In [24]:
numpay.min()

10

In [25]:
numpay.argmax() # max değerinin kaçınçı indexde olduğunu veerir

5

In [26]:
numpay.argmin() # min değerinin kaçınçı indexde olduğunu veerir

4