In [46]:
import numpy as np

In [47]:
# 0.2'den başlayıp 23'e kadar, 2.7 artarak bir dizi oluşturuyoruz.
benimDizim = np.arange(0.2, 23, 2.7)
benimDizim  

array([ 0.2,  2.9,  5.6,  8.3, 11. , 13.7, 16.4, 19.1, 21.8])

In [48]:
# Dizinin 5. indeksindeki değeri alıyoruz
benimDizim[5]

13.7

In [49]:
# Dizinin son elemanını alıyoruz
benimDizim[len(benimDizim)-1]

21.8

In [50]:
# 3. ile 6. indeks arasındaki elemanları alıyoruz (6 dahil değil)
benimDizim[3:6]

array([ 8.3, 11. , 13.7])

In [51]:
# 3. ile 8. indeks arasındaki elemanları 2'şer atlayarak alıyoruz
benimDizim[3:8:2]

array([ 8.3, 13.7, 19.1])

In [52]:
# 3. ile 6. indeks arasındaki elemanları 0 yapıyoruz
benimDizim[3:6:] = 0  
benimDizim 

array([ 0.2,  2.9,  5.6,  0. ,  0. ,  0. , 16.4, 19.1, 21.8])

In [53]:
# 3. ile 8. indeks arasındaki elemanları 2'şer atlayarak alıyoruz
benimDizim[3:8:2]

array([ 0. ,  0. , 19.1])

In [54]:
# 3. ile 6. indeks arasındaki elemanları 0 yapıyoruz
benimDizim[3:6:] = 0  
benimDizim  

array([ 0.2,  2.9,  5.6,  0. ,  0. ,  0. , 16.4, 19.1, 21.8])

In [55]:
# 0'dan başlayıp 24'e kadar bir dizi oluşturuyoruz
dizi2 = np.arange(0, 24)
dizi2  # Yeni dizi görüntülenir

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
# 4. ile 14. indeks arasındaki elemanları slicing yapıyoruz
slicingDizisi = dizi2[4:14]

In [57]:
# slicingDizisi dizisinin tüm elemanlarını 700 yapıyoruz (Dizi2'yi etkiler) Dizi2' de slicing olan elelmanaların değeride değişir
slicingDizisi[:] = 700
slicingDizisi  # Slicing dizisi güncellenmiş

array([700, 700, 700, 700, 700, 700, 700, 700, 700, 700])

In [58]:
# dizi2 üzerinde yapılan değişiklikleri görmek için dizi2'yi kontrol ediyoruz
dizi2

array([  0,   1,   2,   3, 700, 700, 700, 700, 700, 700, 700, 700, 700,
       700,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])