In [55]:
import numpy as np

## Matrix

In [56]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [57]:
# 'benimListem' adlı listeyi numpy array (dizi) formatına dönüştürüyoruz
benimMatrixDizim = np.array(benimListem)

In [58]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [59]:
benimMatrixDizim[0]

array([10, 20, 30])

In [60]:
benimMatrixDizim[1][2]

40

In [61]:
benimMatrixDizim[2,2]

60

In [62]:
# Bu komut, tüm satırları alacak ve her satırın ilk sütununu hariç tutarak, geri kalan tüm sütunları seçer.
benimMatrixDizim[0:, 1:]

array([[20, 30],
       [30, 40],
       [50, 60]])

In [63]:
yeniListe = [[10,20,30,70,80,80,80],[20,30,40,70,80,90,44],[40,50,60,44,55,66,11]]

In [64]:
yeniMatrix = np.array(yeniListe)

In [65]:
yeniMatrix

array([[10, 20, 30, 70, 80, 80, 80],
       [20, 30, 40, 70, 80, 90, 44],
       [40, 50, 60, 44, 55, 66, 11]])

In [66]:
yeniMatrix[[0,2]]

array([[10, 20, 30, 70, 80, 80, 80],
       [40, 50, 60, 44, 55, 66, 11]])

In [67]:
yeniMatrix[0:,2:]

array([[30, 70, 80, 80, 80],
       [40, 70, 80, 90, 44],
       [60, 44, 55, 66, 11]])

In [68]:
yeniMatrix[2,1:]

array([50, 60, 44, 55, 66, 11])

## Numpayda Operasyonlar

In [69]:
dizi1 = np.random.randint(1,99,31)

In [70]:
dizi1

array([65, 52, 32, 34, 14,  3, 69, 41, 63, 51, 74,  7, 61, 27, 61, 21, 53,
       93, 88, 55, 26, 80,  3, 96, 65, 26, 53, 29, 14, 56, 86])

In [71]:
dizi1 > 44 # Dizi1 de 22 den büyük rakamların tespitini yapmaya çalışıyoruz

array([ True,  True, False, False, False, False,  True, False,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
       False, False,  True,  True])

In [72]:
dizi1

array([65, 52, 32, 34, 14,  3, 69, 41, 63, 51, 74,  7, 61, 27, 61, 21, 53,
       93, 88, 55, 26, 80,  3, 96, 65, 26, 53, 29, 14, 56, 86])

In [73]:
sonucDizisi = dizi1 > 44

In [74]:
sonucDizisi

array([ True,  True, False, False, False, False,  True, False,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
       False, False,  True,  True])

In [75]:
sonDizi = np.arange(0,23)

In [76]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44])

In [77]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484])

In [78]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [80]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576])

In [81]:
np.max(sonDizi)

22

In [84]:
np.min(sonDizi)

0